<?php

return [

    /*
     * These are the VAPID keys that will be used for authentication.
     * These can be generated by running 'php artisan webpush:vapid'.
     */
    'vapid' => [
        'subject' => env('VAPID_SUBJECT'),
        'public_key' => env('VAPID_PUBLIC_KEY'),
        'private_key' => env('VAPID_PRIVATE_KEY'),
        'pem' => env('VAPID_PEM_PATH'),
    ],

    /*
     * This is the Google Cloud Messaging API Key.
     */
    'gcm' => [
        'key' => env('GCM_KEY'),
        'sender_id' => env('GCM_SENDER_ID'),
    ],

    /*
     * This is the name of the table that will be created by the migration and
     * used by the WebPushServiceProvider to store push subscriptions.
     */
    'table_name' => 'push_subscriptions',

    /*
     * This is the database connection that will be used by the migration.
     */
    'database_connection' => env('DB_CONNECTION', 'mysql'),

];
